@SmartSolarApi_HostAddress = http://localhost:5031

GET {{SmartSolarApi_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{SmartSolarApi_HostAddress}}/weatherforecast/
Accept: application/json

###
